### PR TITLE
Buttonning

### PR DESCRIPTION
**Pull request by Tzeusy**
toggle.js revamped, added global.js

### CODE REVIEW

**Comment by Yustynn** [comment]
yes

**Comment by gabrielwong159** [comment]
yes

**Comment by Yustynn** [comment]
@gabrielwong159 so basically it changes what toggle does in order to allow for each `Page` instance to have its own keymap `directory`

**Comment by gabrielwong159** [comment]
@Yustynn ``` i love you ```

**Comment by gabrielwong159** [comment]
@Tzeusy ``` fk u ```

**Pull request merged**
